name: Run checks

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build (copy file)
      run: |
        cd ${{ runner.temp }}
        mkdir -p build-outputs
        cp ${{ github.workspace }}/index.html ./build-outputs
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ runner.temp }}/build-outputs
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment
